# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'RTImageX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RTImageX
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'Alamofire'
  pod 'Kingfisher'
end

$static_framework = ['SDWebImage', 'AFNetworking']

pre_install do |install|
  puts install
  install.pod_targets.each {| pod |
    if $static_framework.include?(pod.name)
      def pod.build_type;
        Pod::BuildType.static_framework # 使用静态库
      end
    end
  }
end
